#!/usr/bin/env node

import 'reflect-metadata'
import { Ignitor } from '@adonisjs/core/build/standalone'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { dirname } from 'node:path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

new Ignitor(join(__dirname))
  .httpServer()
  .start()
  .catch(console.error)
